- name: Create webpack.config.js file if non-existent
  template: src=webpack.config.js dest={{ webpack_directory }}/webpack.config.js force=no
  when: webpack_create_config

- name: Create babel.config.js file if non-existent
  template: src=babel.config.js dest={{ webpack_directory }}/babel.config.js force=no
  when: webpack_create_config
