- name: install libapache2-mod-php{{ php_version_installed }}
  apt: pkg=libapache2-mod-php{{ php_version_installed }} state=latest
  become: yes

- apache2_module: state=present name=php{{ php_version_installed }}
  notify: restart apache
  become: yes

- name: Configure mod-php
  command: "{{ phpenmod }} {{ item }}"
  with_items:
    - php-dev
  notify: restart apache
  become: yes

- meta: flush_handlers
