#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

function playbook() {
    ( echo '[docker]' && echo 'localhost ansible_connection=local' ) > ./hosts.ini
    ansible-playbook -i ./hosts.ini --ask-sudo-pass ansible/$1.yml
}

case "$1" in
    start)
        playbook start
        ;;
    up)
        playbook start
        ;;
    stop)
        playbook stop
        ;;
    halt)
        playbook stop
        ;;
    restart)
        playbook restart
        ;;
    status)
        playbook status
        ;;
    enter)
        CID=$(sudo docker ps -l -q)
        PID=$(sudo docker inspect --format "{{ .State.Pid }}" $CID)
        sudo nsenter --target $PID --mount --uts --ipc --net --pid
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac
