---
- fail: msg="'{{ nodejs_version }}' is an invalid version. Please choose between {{nodejs_acceptable_versions|join(', ')}}"
  when: "nodejs_version not in nodejs_acceptable_versions"

- fail: msg="'{{ nodejs_distro }}' is an invalid distro. Please choose between {{nodejs_acceptable_distros|join(', ')}}"
  when: "nodejs_distro not in nodejs_acceptable_distros"

- name: Make sure APT supports HTTPS sources
  apt: pkg=apt-transport-https state=present
  become: yes
- name: Add nodesource.com apt key
  apt_key: id=68576280 url=https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280 state=present
  become: yes
- name: Add nodesource.com apt repo
  apt_repository: repo='deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ nodejs_distro}} main' state=present update_cache=yes
  become: yes
- name: Install nodejs
  apt: name=nodejs state=present
  become: yes

- name: Add Yarn apt key
  apt_key: url=https://dl.yarnpkg.com/debian/pubkey.gpg
  become: yes
  when: nodejs_with_yarn

- name: Add Yarn apt repo
  apt_repository: repo='deb https://dl.yarnpkg.com/debian/ stable main'
  become: yes
  when: nodejs_with_yarn

- name: Install yarn
  apt: pkg=yarn state=latest
  become: yes
  when: nodejs_with_yarn

- name: Create default package.json
  template: src={{ nodejs_package_json_template }} dest={{ nodejs_package_json_path }} force=no
  when: nodejs_create_package_json

- name: Install npm packages
  command: /bin/true
  notify:
    - install package.json
  when: nodejs_install_package_json
