- set_fact: database_type=postgis
- name: set specific variables for distributions
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"

- name: ensure geo packages are installed
  apt:
    pkg:
    - binutils
    - libproj-dev
    - gdal-bin
    - "{{ postgis_package_name }}"
  become: yes

- name: enable database spatially
  command: psql -d {{ database_name }} -c "CREATE EXTENSION IF NOT EXISTS postgis; CREATE EXTENSION IF NOT EXISTS postgis_topology;"
  become_user: postgres
  become: yes
