- set_fact: database_type=postgis

- name: set specific variables for distributions
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"

- name: ensure geo packages are installed
  apt: pkg={{ item }} state=present
  with_items:
    - binutils
    - libproj-dev
    - gdal-bin
    - "{{ postgis_package_name }}"
  become: yes

- include: Debian-7-tasks.yml
  when: ansible_distribution == "Debian" and ansible_distribution_major_version < '8'

- include: default.yml
  when: ansible_distribution != "Debian" or ansible_distribution_major_version > '7'
