- set_fact: database_type=postgis

- name: ensure geo packages are installed
  apt: pkg={{ item }} state=present
  with_items:
      - binutils
      - libproj-dev
      - gdal-bin
      - postgresql-9.1-postgis
  become: yes

- name: ensure postgis database template exists
  postgresql_db: name=template_postgis state=present
  become_user: postgres
  become: yes
  register: postgis_template_created

- name: run postgis scripts on postgis database template
  command: psql -d template_postgis --file '/usr/share/postgresql/9.1/contrib/postgis-1.5/{{ item }}'
  with_items:
    - postgis.sql
    - spatial_ref_sys.sql
  become_user: postgres
  become: yes
  when: postgis_template_created|changed

- name: run postgis scripts on existing database
  command: psql -d {{ database_name }} --file /usr/share/postgresql/9.1/contrib/postgis-1.5/{{ item }}
  become_user: postgres
  become: yes
  with_items:
    - postgis.sql
    - spatial_ref_sys.sql
