- name: Create SOLR group
  group: name=solr state=present
  become: yes

- name: Create SOLR user
  user: name=solr group=solr groups="www-data" comment="Solr Daemon" home="{{ solr_install_dir }}"
  become: yes

- name: Download SOLR v{{ solr_version }}
  get_url: url={{ solr_url }} dest={{ solr_install_dir }}/solr-{{ solr_version }}.tgz
  become_user: solr
  become: yes

- name: Extract SOLR
  command: tar xzf {{ solr_install_dir }}/solr-{{ solr_version }}.tgz --strip 1 -C {{ solr_install_dir }}/
  become_user: solr
  become: yes

- name: Add Core directory
  when: solr_core_name is defined and solr_core_conf is defined
  file:
    path: "{{ solr_config_dir}}/{{ solr_core_name}}"
    state: directory
  become_user: solr
  become: yes

- name: Symlink Core conf
  when: solr_core_name is defined and solr_core_conf is defined
  file:
    src: "{{ solr_core_conf }}"
    dest: "{{ solr_config_dir}}/{{ solr_core_name}}/conf"
    state: link
  become_user: solr
  become: yes

- name: Setup Core properties file
  when: solr_core_name is defined and solr_core_conf is defined
  copy:
    content: "name={{ solr_core_name}}"
    dest: "{{ solr_config_dir}}/{{ solr_core_name}}/core.properties"
  become_user: solr
  become: yes

- name: SOLR config directory permission
  file: dest="{{ solr_config_dir }}" state=directory group=solr mode="g+rwX" recurse=yes
  become: yes

- name: SOLR install directory permission
  file: dest="{{ solr_install_dir }}" state=directory owner=solr group=www-data recurse=yes
  become: yes
  notify: restart supervisor

- meta: flush_handlers
