- name: disable strict host checking
  lineinfile: dest=~/.ssh/config owner=vagrant mode=0600 line="StrictHostKeyChecking no" create="yes"
  when: "{{ ssh_no_stricthostkeychecking|default(false) }} == true"

- name: add gitlab.liip.ch ssh host key
  lineinfile: dest=~/.ssh/known_hosts owner=vagrant mode=0600  create="yes" line="|1|kpxP5RUzhsD0D+Orj+cIyYVnMng=|svlMzQRFnzhsXteU7cS8W8ymPl4= ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICQDU/qcjvPfFV/wdl/s0IJQgRl9LVnGONMLVsn6m780"

- name: add gitlab.liip.ch ssh host key line 2
  lineinfile: dest=~/.ssh/known_hosts owner=vagrant mode=0600  create="yes" line="|1|jkSRq0bFi+OikrNAmZJ+cvSyK+Y=|TCifULANLTMa8LnJesE+DCnpwaQ= ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICQDU/qcjvPfFV/wdl/s0IJQgRl9LVnGONMLVsn6m780"


- name: add github.com ssh host key
  lineinfile: dest=~/.ssh/known_hosts owner=vagrant mode=0600  create="yes" line="|1|QZNAYtd7C+pZl2VXmAsDp6Pm0/c=|pTECnHRaAZ+kqep4FKry9MhYiu8= ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="

